### ISSUE TITLE
new null-safe branche

### ISSUE THREAD

**Issue by noaman813** [iamSahdeep/fu_uber#4]
I've cloned your project put I get this error. 
is there a thing I need to add except the API key

`
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':geolocator:processDebugManifest'.
> Failed to calculate the value of task ':geolocator:processDebugManifest' property 'packageOverride'.
   > Failed to query the value of property 'applicationId'.
      > org.xml.sax.SAXParseException; systemId: file:/C:/flutter/.pub-cache/hosted/pub.dartlang.org/geolocator-7.0.3/android/src/main/AndroidManifest.xml; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org`

**Comment by iamSahdeep** [comment]
Seems like android manifest have some problem, let me check after some time and get back to you

**Comment by noaman813** [comment]
ok thanks <3

**Comment by iamSahdeep** [comment]
@noaman813 I can't repro the issue, app is running for me, even on new/fresh clone. Did you switched to `nullsafe` branch after cloning. If yes, can please try flutter clean etc.

Plus the issue seems related to `geolocator` plugin. You can try remove that from pubsec in `nullsafe` branch (we are not using it now)

**Comment by iamSahdeep** [comment]
Closing now.
